# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpo < Formula
  desc "Minimal CLI time tracker for developers"
  homepage "https://github.com/DylanDevelops/tmpo"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.2/tmpo_0.10.2_Darwin_x86_64.tar.gz"
      sha256 "f12a5bcc4dddfc347073902e70f1461f189ab7ad8d4bd3f1b6614f0c6cc80dd3"

      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.2/tmpo_0.10.2_Darwin_arm64.tar.gz"
      sha256 "166c6c68b7719ee6a8e28d78de2233cc65cb6ae88a3b3d2a06db522a1536f1dc"

      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.2/tmpo_0.10.2_Linux_x86_64.tar.gz"
      sha256 "290460641cb71b43886b379ce2fc2b6c4583974d747093733efa1e727e4b4555"
      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.2/tmpo_0.10.2_Linux_arm64.tar.gz"
      sha256 "49b4fd18502cf9130ca7644c2ffcd4fbbae402b9e9541fe75df8cd7f5edcc9d2"
      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
  end
end
