# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpo < Formula
  desc "Minimal CLI time tracker for developers"
  homepage "https://github.com/DylanDevelops/tmpo"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.0/tmpo_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "1f30811b45ef2f6d40fe0398466da3841e578d3c0b073df8c6b8c15cf73c1025"

      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.0/tmpo_0.10.0_Darwin_arm64.tar.gz"
      sha256 "9a525d18703f6d8f2579930067b8765578117882019397b7eaa15e83d56d70c3"

      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.0/tmpo_0.10.0_Linux_x86_64.tar.gz"
      sha256 "9d55c02aae387fd70da76862813111b78146de494e38400431e215f659f838fb"
      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.10.0/tmpo_0.10.0_Linux_arm64.tar.gz"
      sha256 "2726daefafdf7e55205c0cc8f0e062488091159c8f1b82e9cf097eb70eca78e0"
      define_method(:install) do
        bin.install "tmpo"
        generate_completions_from_executable(bin/"tmpo", "completion")
      end
    end
  end
end
